const $list = [
    ["absent", "欠席の、不在の"],
    ["afraid", "怖れる"],
    ["alone", "孤独な、ひとりで"],
    ["angry", "怒っている"],
    ["cheap", "安い"],
    ["dangerous", "危険な"],
    ["excited", "興奮した"],
    ["expensive", "(値段が)高い"],
    ["far", "遠い"],
    ["free", "自由な、ひまな/無料の"],
    ["glad", "うれしい"],
    ["hard", "難しい/固い/一生懸命"],
    ["local", "地方の / 地元の"],
    ["natural", "自然の"],
    ["necessary", "必要な"],
    ["present", "現在の/出席している"],
    ["sick", "病気の"],
    ["strange", "変わった、奇妙な"],
    ["true", "本当の"],
    ["warm", "温かい、暖かい"],
    ["careful", "注意深い、慎重な"],
    ["convenient", "便利な"],
    ["cute", "かわいい"],
    ["deep", "深い"],
    ["funny", "面白い"],
    ["empty", "空の"],
    ["full", "いっぱいの"],
    ["healthy", "健康な"],
    ["heavy", "重い"],
    ["impossible", "不可能な"],
    ["lucky", "幸運な"],
    ["perfect", "完全な"],
    ["possible", "可能な"],
    ["quiet", "静かな"],
    ["ready", "準備ができている"],
    ["real", "現実の、本当の"],
    ["safe", "安全な"],
    ["wide", "(幅が)広い"],
    ["tall", "背が高い"],
    ["large", "大きい、広い"],
    ["quick", "素早い"],
    ["cool", "涼しい / かっこいい"],
    ["fantastic", "素晴らしい"],
    ["fine", "よい"],
    ["daily", "毎日の、日常の"]
];