const $list = [
    ["asleep", "眠っている"],
    ["active", "活発な、アクティブな"],
    ["alive", "生きている"],
    ["basic", "基本的な、基礎の"],
    ["broad", "(幅が)広い"],
    ["central", "中央の"],
    ["correct", "正確な"],
    ["creative", "創造的な"],
    ["dirty", "汚い"],
    ["dry", "乾いている"],
    ["fat", "太った"],
    ["honest", "正直な"],
    ["narrow", "(幅が)せまい"],
    ["polite", "礼儀正しい、丁寧な"],
    ["tough", "困難な"],
    ["wet", "濡れている"],
    ["wise", "賢い"],
    ["comfortable", "快適な、気持ちいい"],
    ["certain", "確かな / とある"],
    ["classic", "古典的な"],
    ["colorful", "カラフルな"],
    ["efficient", "効率のよい"],
    ["golden", "金色の"],
    ["flat", "平らな"],
    ["latest", "最新の"],
    ["limited", "限定的な、限定の"],
    ["opposite", "反対の"],
    ["pale", "顔色の悪い、青白い"],
    ["private", "個人的な / 私立の"],
    ["professional", "プロ/専門の"],
    ["regular", "規則正しい、通常の"],
    ["ridiculous", "ばかげた、愚かな"],
    ["skillful", "技術のある、熟練した"],
    ["terrible", "恐ろしい / ひどい"],
    ["usual", "いつもの"],
    ["wooden", "木の、木製の"],
    ["ancient", "古代の"],
    ["artificial", "人工の"],
    ["chemical", "化学の"],
    ["depressed", "落胆した"],
    ["former", "以前の / 前の"],
    ["humid", "湿気のある"],
    ["industrial", "産業の"],
    ["medical", "医療の"],
    ["minor", "小さな / より下の"],
    ["missing", "行方不明の / 失われた"],
    ["modern", "現代の、現代的な"],
    ["ordinary", "普通の"],
    ["physical", "身体的な / 物理的な"],
    ["political", "政治的な"],
    ["responsible", "責任のある"],
    ["sore", "痛い"],
    ["successful", "成功している"],
    ["tender", "やさしい"],
    ["vast", "広大な"]
];
