const $list = [
    ["age", "年齢 / 時代"],
    ["communication", "コミュニケーション"],
    ["concert", "コンサート"],
    ["dictionary", "辞書"],
    ["donut", "ドーナツ"],
    ["farm", "農場"],
    ["floor", "床 / ～階"],
    ["garden", "庭"],
    ["gift", "贈り物"],
    ["goal", "ゴール、目標"],
    ["gold", "金"],
    ["ground", "グラウンド、地面"],
    ["half", "半分、半分の"],
    ["hall", "ホール"],
    ["health", "健康"],
    ["husband", "夫"],
    ["island", "島"],
    ["line", "線、列"],
    ["medicine", "薬"],
    ["everything", "何でも"],
    ["mistake", "間違い / ～を間違える"],
    ["moon", "月"],
    ["order", "注文(する) / 命令(する)"],
    ["piano", "ピアノ"],
    ["plane", "飛行機"],
    ["seat", "席"],
    ["shoe", "靴"],
    ["side", "側面、側"],
    ["stone", "石"],
    ["test", "テスト/～をテストする"],
    ["top", "頂点、頂上"],
    ["tour", "旅行"],
    ["type", "タイプ、型"],
    ["wall", "壁"],
    ["weather", "天気"],
    ["wife", "妻"],
    ["window", "窓"],
    ["worker", "労働者"],
    ["writer", "作家、ライター"],
    ["the United States", "アメリカ合衆国"]
];