const $list = [
    ["bar", "棒 / バー(酒場)"],
    ["bean", "豆"],
    ["bee", "ハチ"],
    ["beginning", "始まり"],
    ["birth", "誕生"],
    ["blood", "血"],
    ["bowl", "ボウル、お椀"],
    ["candle", "ろうそく"],
    ["chain", "鎖、チェーン"],
    ["copy", "コピー/～をコピーする"],
    ["couple", "ひと組、夫婦/カップル"],
    ["discussion", "議論"],
    ["factory", "工場"],
    ["female", "女性(の)"],
    ["foreigner", "外国人"],
    ["form", "形/形式、～を形づくる"],
    ["goods", "品物"],
    ["grass", "草、芝生"],
    ["guest", "ゲスト、客"],
    ["brightness", "明るさ"],
    ["hill", "丘"],
    ["land", "土地/陸、着陸する"],
    ["leaf", "葉"],
    ["list", "リスト"],
    ["male", "男性(の)"],
    ["quarter", "4分の1"],
    ["record", "記録 / ～を記録する"],
    ["safety", "安全"],
    ["secret", "秘密(の)"],
    ["service", "サービス"],
    ["society", "社会"],
    ["stew", "シチュー"],
    ["stress", "ストレス / 強調"],
    ["taste", "味 / ～を味わう"],
    ["topic", "トピック、話題"],
    ["training", "トレーニング"],
    ["understanding", "理解"],
    ["wine", "ワイン"],
    ["yard", "庭 / ヤード(0.9m)"],
    ["zone", "ゾーン、地帯"]
];

