const $list = [
    ["board", "板"],
    ["brain", "脳"],
    ["captain", "キャプテン"],
    ["chess", "チェス"],
    ["climate", "気候"],
    ["community", "地域社会、コミュニティ"],
    ["disaster", "災害"],
    ["drama", "ドラマ"],
    ["entertainment", "娯楽"],
    ["expert", "専門家、エキスパート"],
    ["farewell", "別れ"],
    ["flight", "フライト、飛ぶこと"],
    ["freedom", "自由"],
    ["fridge", "冷蔵庫"],
    ["fuel", "燃料"],
    ["humor", "ユーモア"],
    ["injury", "けが"],
    ["lamp", "ランプ、灯り"],
    ["movement", "動き / 社会運動"],
    ["developing country", "発展途上国"],
    ["palm", "手のひら"],
    ["panel", "パネル"],
    ["passion", "情熱"],
    ["phrase", "フレーズ、言い回し"],
    ["poison", "毒"],
    ["product", "製品、作物"],
    ["resource", "資源"],
    ["shade", "影"],
    ["soldier", "兵士"],
    ["stomachache", "胃痛、腹痛"],
    ["temperature", "温度、気温"],
    ["tale", "物語"],
    ["tradition", "伝統"],
    ["turkey", "七面鳥"],
    ["sunset", "夕日、日没"],
    ["symbol", "シンボル、印"],
    ["throat", "のど"],
    ["tourism", "観光(業)"],
    ["turtle", "カメ"],
    ["waterfall", "滝"]
];

