const $list = [
    ["accident", "事故 / 偶然"],
    ["adult", "大人"],
    ["aquarium", "水族館"],
    ["amount", "量 / 総額"],
    ["bathroom", "浴室、トイレ"],
    ["bottle", "ビン"],
    ["business", "ビジネス、仕事"],
    ["button", "ボタン"],
    ["century", "世紀"],
    ["Christmas", "クリスマス"],
    ["circle", "丸 / 丸い"],
    ["cloth", "布"],
    ["company", "会社"],
    ["court", "コート / 法廷"],
    ["danger", "危険"],
    ["death", "死"],
    ["dentist", "歯医者"],
    ["design", "デザイン/～を設計する"],
    ["difference", "違い"],
    ["education", "教育"],
    ["electricity", "電気"],
    ["elevator", "エレベーター"],
    ["energy", "エネルギー"],
    ["environment", "環境"],
    ["fashion", "ファッション、流行"],
    ["French", "フランス語/人、フランスの"],
    ["god", "神"],
    ["hero", "ヒーロー、英雄"],
    ["human", "人間"],
    ["leader", "リーダー"],
    ["magnet", "磁石"],
    ["meaning", "意味"],
    ["memory", "記憶"],
    ["menu", "メニュー"],
    ["middle", "真ん中、中間"],
    ["million", "百万"],
    ["mirror", "鏡"],
    ["ocean", "大海"],
    ["opinion", "意見"],
    ["prize", "賞"],
    ["program", "プログラム/番組"],
    ["project", "プロジェクト"],
    ["promise", "約束 / ～を約束する"],
    ["rectangle", "長方形"],
    ["report", "報告 / ～を報告する"],
    ["result", "結果"],
    ["schedule", "スケジュール"],
    ["scientist", "科学者"],
    ["shape", "形"],
    ["Spanish", "スペイン語/人、スペインの"],
    ["staff", "スタッフ"],
    ["stage", "ステージ、舞台"],
    ["stairs", "階段"],
    ["task", "仕事、タスク"],
    ["title", "タイトル、題名"],
    ["total", "合計"],
    ["tourist", "観光客"],
    ["trouble", "トラブル、問題"],
    ["visitor", "訪問者"],
    ["the Olympic Games", "オリンピック"]
];