const $list = [
    ["ambulance", "救急車"],
    ["beauty", "美しさ"],
    ["blackboard", "黒板"],
    ["bubble", "泡"],
    ["capital", "首都"],
    ["cause", "原因/～の原因となる"],
    ["chart", "図表"],
    ["comment", "コメント"],
    ["decision", "決定、決心"],
    ["earthquake", "地震"],
    ["engineer", "技術者、エンジニア"],
    ["entrance", "入り口"],
    ["favor", "お願い"],
    ["film", "フィルム、映画"],
    ["firework", "花火"],
    ["generation", "世代 / 同世代の人々"],
    ["locker", "ロッカー"],
    ["manner", "マナー"],
    ["model", "モデル(型、模型)"],
    ["national holiday", "祝日"],
    ["neighbor", "隣人"],
    ["owner", "所有者"],
    ["pack", "箱/パック、～を詰める"],
    ["poem", "詩"],
    ["population", "人口"],
    ["programmer", "プログラマー"],
    ["sadness", "悲しみ"],
    ["seed", "種"],
    ["shelf", "棚"],
    ["situation", "状況"],
    ["smoke", "煙 / タバコを吸う"],
    ["spell", "スペル、つづり"],
    ["style", "型、スタイル"],
    ["tear", "涙"],
    ["tie", "ネクタイ"],
    ["trade", "貿易/取引、取引する"],
    ["victory", "勝利"],
    ["wire", "針金、ワイヤー"],
    ["United Nations", "国連"],
    ["technology", "テクノロジー(科学技術)"]
];


