const $list = [
    ["athlete", "アスリート、運動選手"],
    ["barrier", "障壁"],
    ["carbon", "炭素"],
    ["catalog", "カタログ"],
    ["cave", "洞窟"],
    ["cell", "細胞"],
    ["ceremony", "式典"],
    ["childhood", "こどもの頃"],
    ["courage", "勇気"],
    ["creativity", "創造力"],
    ["decade", "10年"],
    ["desert", "砂漠"],
    ["direction", "方向、指示"],
    ["discount", "割引"],
    ["discovery", "発見"],
    ["economy", "経済"],
    ["facility", "施設、設備"],
    ["furniture", "家具"],
    ["fiction", "フィクション"],
    ["advertisement", "広告"],
    ["globe", "地球、球体"],
    ["heaven", "天国"],
    ["interpreter", "通訳者"],
    ["knowledge", "知識"],
    ["lawyer", "弁護士"],
    ["marathon", "マラソン"],
    ["matter", "問題"],
    ["mystery", "謎"],
    ["official", "公式 / 公式の"],
    ["panic", "パニック(の)"],
    ["professor", "教授"],
    ["recipe", "レシピ"],
    ["relay", "リレー"],
    ["string", "糸、紐"],
    ["suburb", "郊外"],
    ["survey", "調査"],
    ["vote", "投票 / ～に投票する"],
    ["hay fever", "花粉症"],
    ["renewable energy", "再生可能エネルギー"],
    ["dot", "点"],
    ["object", "物体 / 目的"],
    ["scenery", "風景、景色"]
];


