const $list = [
    ["autumn", "秋"],
    ["baseball", "野球"],
    ["basketball", "バスケットボール"],
    ["building", "建物"],
    ["care", "世話、注意/～を気にかける"],
    ["college", "大学"],
    ["earth", "地球"],
    ["fall", "秋"],
    ["forest", "森"],
    ["Japanese", "日本人/日本語/日本の"],
    ["map", "地図"],
    ["math", "数学"],
    ["message", "メッセージ"],
    ["movie", "映画"],
    ["museum", "博物館、美術館"],
    ["plant", "植物"],
    ["road", "道路"],
    ["elementary school", "小学校"],
    ["high school", "高校"],
    ["junior high school", "中学校"],
    ["season", "季節"],
    ["ski", "スキー"],
    ["speech", "スピーチ"],
    ["soccer", "サッカー"],
    ["sound", "音 / ～に聞こえる"],
    ["sport", "スポーツ"],
    ["spring", "春"],
    ["store", "店"],
    ["summer", "夏"],
    ["supermarket", "スーパー"],
    ["swimming", "水泳"],
    ["taxi", "タクシー"],
    ["tennis", "テニス"],
    ["theater", "映画館、劇場"],
    ["university", "大学"],
    ["volleyball", "バレーボール"],
    ["way", "道 / 方法"],
    ["winter", "冬"],
    ["world", "世界"],
    ["zoo", "動物園"]
];
