// 単語帳セット1
const VOCAB_SET_1 = [
    ['cut', 'cut', 'cut'],
    ['hit', 'hit', 'hit'],
    ['hurt', 'hurt', 'hurt'],
    ['put', 'put', 'put'],
    ['read', 'read', 'read'],
    ['set', 'set', 'set'],
    ['come', 'came', 'come'],
    ['become', 'became', 'become'],
    ['run', 'ran', 'run'],
    ['pay', 'paid', 'paid'],
    ['say', 'said', 'said'],
    ['build', 'built', 'built'],
    ['lend', 'lent', 'lent'],
    ['send', 'sent', 'sent'],
    ['spend', 'spent', 'spent'],
    ['lose', 'lost', 'lost'],
    ['get', 'got', 'got'],
    ['forget', 'forgot', 'forgot(forgotten)'],
    ['hold', 'held', 'held'],
    ['sit', 'sat', 'sat'],
    ['win', 'won', 'won'],
    ['find', 'found', 'found'],
    ['have', 'had', 'had'],
    ['hear', 'heard', 'heard'],
    ['make', 'made', 'made'],
    ['meet', 'met', 'met'],
    ['feel', 'felt', 'felt'],
    ['keep', 'kept', 'kept'],
    ['sleep', 'slept', 'slept'],
    ['leave', 'left', 'left']
];

// 単語帳セット2
const VOCAB_SET_2 = [
    ['sell', 'sold', 'sold'],
    ['tell', 'told', 'told'],
    ['buy', 'bought', 'bought'],
    ['bring', 'brought', 'brought'],
    ['think', 'thought', 'thought'],
    ['catch', 'caught', 'caught'],
    ['teach', 'taught', 'taught'],
    ['stand', 'stood', 'stood'],
    ['understand', 'understood', 'understood'],
    ['do', 'did', 'done'],
    ['go', 'went', 'gone'],
    ['draw', 'drew', 'drawn'],
    ['fly', 'flew', 'flown'],
    ['grow', 'grew', 'grown'],
    ['know', 'knew', 'known'],
    ['throw', 'threw', 'thrown'],
    ['drive', 'drove', 'driven'],
    ['fall', 'fell', 'fallen'],
    ['give', 'gave', 'given'],
    ['write', 'wrote', 'written'],
    ['eat', 'ate', 'eaten'],
    ['see', 'saw', 'seen'],
    ['take', 'took', 'taken'],
    ['break', 'broke', 'broken'],
    ['speak', 'spoke', 'spoken'],
    ['begin', 'began', 'begun'],
    ['drink', 'drank', 'drunk'],
    ['sing', 'sang', 'sung'],
    ['swim', 'swam', 'swum']
];