const $list = [
    ["ancient", "古代の"],
    ["artificial", "人工の"],
    ["chemical", "化学の"],
    ["depressed", "落胆した"],
    ["former", "以前の / 前の"],
    ["hopeless", "絶望した、望みのない"],
    ["humid", "湿気のある"],
    ["industrial", "産業の"],
    ["medical", "医療の"],
    ["minor", "小さな / より下の"],
    ["missing", "行方不明の / 失われた"],
    ["modern", "現代の、現代的な"],
    ["ordinary", "普通の、通常の"],
    ["physical", "身体的な / 物理的な"],
    ["political", "政治的な"],
    ["responsible", "責任のある"],
    ["sore", "痛い"],
    ["successful", "成功している"],
    ["tender", "やさしい"],
    ["vast", "広大な"]
];