const $list = [
    ["abroad", "海外へ、海外で"],
    ["anymore", "(否定文)もう～ない"],
    ["anyway", "とにかく、いずれにせよ"],
    ["carefully", "注意深く、慎重に"],
    ["certainly", "もちろん、確かに"],
    ["clearly", "はっきりと"],
    ["deeply", "深く"],
    ["especially", "特に"],
    ["exactly", "正確には/まさにその通り"],
    ["over", "(副詞)終わる"],
    ["probably", "おそらく"],
    ["quietly", "静かに"],
    ["quite", "とても"],
    ["sincerely", "心から、真摯に"],
    ["slowly", "ゆっくり"],
    ["still", "いまだに"],
    ["straight", "真っすぐ"],
    ["strongly", "強く"],
    ["suddenly", "突然"],
    ["tonight", "今夜"]
];