const $list = [
    ["everybody", "誰でも、皆"],
    ["nobody", "誰も～ない"],
    ["everywhere", "どこでも"],
    ["somewhere", "どこかに/で"],
    ["anywhere", "どこでも"],
    ["anytime", "いつでも"],
    ["either", "～もまた(ない)、どちらか/でも"],
    ["neither", "どちらも～ない"],
    ["ahead", "前方に"],
    ["overseas", "海外・外国へ/に"],
    ["past", "(副詞)通り過ぎて / 過去"],
    ["perhaps", "多分"],
    ["downstairs", "階下で/に"],
    ["upstairs", "上階で/に"],
    ["aboard", "(乗り物)に乗って"],
    ["against", "～に反対して/逆らって"],
    ["beside", "～のそばに"],
    ["toward", "～の方へ、～に向かって"],
    ["upon", "～の上に"]
];