const $list = [
    ["brave", "勇敢な"],
    ["blind", "目の不自由な"],
    ["eastern", "東の、東部の"],
    ["international", "国際的な"],
    ["junior", "年下の、下級の"],
    ["mysterious", "不思議な、不可解な"],
    ["national", "国の、国民の"],
    ["native", "生まれつきの"],
    ["northern", "北の、北部の"],
    ["plastic", "プラスチック/ビニールの"],
    ["public", "公共の、公の"],
    ["senior", "年上の、上級の"],
    ["snowy", "雪の"],
    ["solar", "太陽の"],
    ["southern", "南の、南部の"],
    ["unique", "独特の、珍しい"],
    ["used", "中古の"],
    ["western", "西の、西洋/欧米の"],
    ["whole", "全体の、全ての"]
];