const $list = [
    ["mistake", "間違い / ～を間違える"],
    ["moon", "月"],
    ["order", "注文(する) / 命令(する)"],
    ["piano", "ピアノ"],
    ["plane", "飛行機"],
    ["seat", "席"],
    ["shoe", "靴"],
    ["side", "側面、側"],
    ["stone", "石"],
    ["test", "テスト/～をテストする"],
    ["top", "頂点、頂上"],
    ["tour", "旅行"],
    ["type", "タイプ、型"],
    ["wall", "壁"],
    ["weather", "天気"],
    ["wife", "妻"],
    ["window", "窓"],
    ["worker", "労働者"],
    ["writer", "作家、ライター"]
];