const $list = [
    ["crowded", "混雑した"],
    ["elderly", "年配の"],
    ["elementary", "基本の、初級の"],
    ["equal", "平等な、等しい"],
    ["homesick", "ホームシック(の)"],
    ["huge", "巨大な"],
    ["impressive", "印象的な、感動的な"],
    ["living", "生きている"],
    ["major", "主要な、大きな"],
    ["negative", "消極的な、否定的な"],
    ["nervous", "緊張した、神経質な"],
    ["peaceful", "平和な"],
    ["positive", "積極的な、前向きな"],
    ["round", "丸い / 円 / 回る"],
    ["scary", "怖ろしい"],
    ["shiny", "輝いている"],
    ["single", "たった1つの、ひとり用の"],
    ["thick", "厚い"],
    ["thin", "薄い、やせた"],
    ["worried", "心配している"]
];