const $list = [
    ["peach", "桃"],
    ["pie", "パイ"],
    ["pilot", "パイロット"],
    ["pineapple", "パイナップル"],
    ["pizza", "ピザ"],
    ["plan", "計画 / ～を計画する"],
    ["queen", "女王"],
    ["radish", "大根"],
    ["rocket", "ロケット"],
    ["rose", "バラ"],
    ["restroom", "トイレ"],
    ["right", "右"],
    ["ruler", "定規"],
    ["sandwich", "サンドイッチ"],
    ["scissors", "はさみ"],
    ["shirt", "シャツ"],
    ["shoulder", "肩"],
    ["shrine", "神社"]
];