const $list = [
    ["palm", "手のひら"],
    ["panel", "パネル"],
    ["passion", "情熱"],
    ["phrase", "フレーズ、言い回し"],
    ["poison", "毒"],
    ["product", "製品、作物"],
    ["resource", "資源"],
    ["shade", "影"],
    ["soldier", "兵士"],
    ["stomachache", "胃痛、腹痛"],
    ["temperature", "温度、気温"],
    ["tale", "物語"],
    ["tradition", "伝統"],
    ["turkey", "七面鳥"],
    ["sunset", "夕日、日没"],
    ["symbol", "シンボル、印"],
    ["throat", "のど"],
    ["tourism", "観光(業)"],
    ["turtle", "カメ"],
    ["waterfall", "滝"]
];