const $list = [
    ["Africa", "アフリカ"],
    ["America", "アメリカ"],
    ["Asia", "アジア"],
    ["Australia", "オーストラリア"],
    ["Brazil", "ブラジル"],
    ["Britain", "イギリス"],
    ["Canada", "カナダ"],
    ["China", "中国"],
    ["Europe", "ヨーロッパ"],
    ["France", "フランス"],
    ["Germany", "ドイツ"],
    ["India", "インド"],
    ["Indonesia", "インドネシア"],
    ["Italy", "イタリア"],
    ["Korea", "韓国"],
    ["Russia", "ロシア"],
    ["Singapore", "シンガポール"],
    ["Spain", "スペイン"],
    ["Thailand", "タイ"],
    ["Vietnam", "ベトナム"]
];