const $list = [
    ["afternoon", "午後"],
    ["animal", "動物"],
    ["bag", "バッグ"],
    ["bike", "自転車"],
    ["bird", "鳥"],
    ["birthday", "誕生日"],
    ["book", "本"],
    ["boy", "男の子"],
    ["brother", "兄弟"],
    ["bus", "バス"],
    ["car", "車"],
    ["class", "クラス、授業"],
    ["club", "クラブ"],
    ["country", "国"],
    ["day", "日 / 日中"],
    ["doctor", "医者 / 博士"],
    ["dog", "犬"],
    ["dream", "夢 / 夢を見る"],
    ["English", "英語(の)"],
    ["family", "家族"]
];