const $list = [
    ["airport", "空港"],
    ["album", "アルバム"],
    ["arm", "腕"],
    ["bank", "銀行 / 土手"],
    ["boat", "ボート"],
    ["bridge", "橋"],
    ["camera", "カメラ"],
    ["center", "中心、センター"],
    ["cloud", "雲"],
    ["coat", "コート"],
    ["coin", "コイン"],
    ["dancer", "ダンサー"],
    ["diary", "日記"],
    ["dollar", "ドル"],
    ["driver", "運転手"],
    ["drugstore", "薬局"],
    ["examination", "試験"],
    ["field", "野原、フィールド"],
    ["fire", "火、火事"],
    ["greeting", "あいさつ"]
];