const $list = [
    ["match", "試合、勝負"],
    ["meter", "メートル"],
    ["octopus", "タコ"],
    ["peace", "平和"],
    ["percent", "パーセント"],
    ["performance", "演技、演奏"],
    ["poster", "ポスター"],
    ["presentation", "発表、プレゼンテーション"],
    ["reality", "現実、実際"],
    ["section", "部分、部門"],
    ["sense", "感覚 / 意味"],
    ["skill", "技術、スキル"],
    ["stationery", "文房具"],
    ["thought", "考え、思考"],
    ["tool", "道具 / 手段"],
    ["tower", "タワー"],
    ["track", "軌道・線路 / 陸上のトラック"],
    ["tuna", "マグロ"],
    ["wheel", "車輪"]
];