const $list = [
    ["myself", "自分自身(を/に)"],
    ["yourself", "あなた(たち)自身(を/に)"],
    ["himself", "彼自身(を/に)"],
    ["herself", "彼女自身(を/に)"],
    ["itself", "それ自体(を/に)"],
    ["ourselves", "私たち自身(を/に)"],
    ["themselves", "彼ら/彼女ら/それら自身"],
    ["above", "～の上に"],
    ["below", "～の下に"],
    ["behind", "～の後ろに"],
    ["along", "～に沿って"],
    ["else", "その他の/に"],
    ["off", "離れて"],
    ["forward", "前へ"],
    ["instead", "代わりに"],
    ["twice", "2回"],
    ["less", "～より少ない / 少なく"],
    ["although", "～だが"]
];