const $list = [
    ["advertisement", "広告"],
    ["athlete", "アスリート、運動選手"],
    ["barrier", "障壁"],
    ["carbon", "炭素"],
    ["catalog", "カタログ"],
    ["cave", "洞窟"],
    ["cell", "細胞"],
    ["ceremony", "式典"],
    ["childhood", "こどもの頃"],
    ["courage", "勇気"],
    ["creativity", "創造力"],
    ["decade", "10年"],
    ["desert", "砂漠"],
    ["direction", "方向、指示"],
    ["discount", "割引"],
    ["discovery", "発見"],
    ["economy", "経済"],
    ["facility", "施設、設備"],
    ["furniture", "家具"],
    ["fiction", "フィクション"]
];