const $list = [
    ["shrine", "神社"],
    ["snake", "ヘビ"],
    ["south", "南"],
    ["square", "正方形"],
    ["stapler", "ホッチキス"],
    ["strawberry", "イチゴ"],
    ["sweater", "セーター"],
    ["teeth", "歯(複数形)"],
    ["telephone", "電話"],
    ["temple", "寺"],
    ["toe", "つま先"],
    ["tooth", "歯(単数形)"],
    ["triangle", "三角形"],
    ["umbrella", "傘"],
    ["vegetable", "野菜"],
    ["vest", "ベスト(服)"],
    ["watermelon", "スイカ"],
    ["west", "西"],
    ["wolf", "オオカミ"],
    ["zebra", "シマウマ"]
];