const $list = [
    ["completely", "完全に"],
    ["dear", "親愛なる"],
    ["differently", "(～と)異なって"],
    ["extra", "余分の、追加の"],
    ["happily", "幸せに"],
    ["including", "～を含めて"],
    ["incredibly", "信じられないことに"],
    ["nearly", "ほとんど"],
    ["online", "オンラインで/の"],
    ["originally", "元々、本来"],
    ["precisely", "正確に"],
    ["rather", "かなり"],
    ["recently", "最近"],
    ["safely", "安全に"],
    ["seriously", "真剣に、深刻に"],
    ["someday", "いつか"],
    ["truly", "本当に"],
    ["whether", "～かどうか"]
];