const $list = [
    ["gym", "体育館"],
    ["hair", "髪"],
    ["hamburger", "ハンバーガー"],
    ["ink", "インク"],
    ["internet", "インターネット"],
    ["juice", "ジュース"],
    ["knee", "ひざ"],
    ["knife", "ナイフ"],
    ["koala", "コアラ"],
    ["lake", "湖"],
    ["left", "左"],
    ["leg", "脚"],
    ["lettuce", "レタス"],
    ["melon", "メロン"],
    ["mushroom", "キノコ"],
    ["newspaper", "新聞"],
    ["north", "北"],
    ["nuts", "ナッツ"],
    ["pants", "ズボン"],
    ["party", "パーティー"]
];