const $list = [
    ["bar", "棒 / バー(酒場)"],
    ["bean", "豆"],
    ["bee", "ハチ"],
    ["beginning", "始まり"],
    ["birth", "誕生"],
    ["blood", "血"],
    ["bowl", "ボウル、お椀"],
    ["candle", "ろうそく"],
    ["chain", "鎖、チェーン"],
    ["copy", "コピー/～をコピーする"],
    ["couple", "ひと組、夫婦/カップル"],
    ["discussion", "議論"],
    ["factory", "工場"],
    ["female", "女性(の)"],
    ["foreigner", "外国人"],
    ["form", "形/形式、～を形づくる"],
    ["goods", "品物"],
    ["grass", "草、芝生"],
    ["guest", "ゲスト、客"]
];