const $list = [
    ["story", "ストーリー、話"],
    ["street", "通り"],
    ["student", "学生"],
    ["tea", "紅茶"],
    ["teacher", "先生"],
    ["team", "チーム"],
    ["time", "時間"],
    ["today", "今日"],
    ["tomorrow", "明日"],
    ["town", "町"],
    ["train", "電車 / ～を特訓する"],
    ["travel", "旅行 / 旅行する"],
    ["tree", "木"],
    ["trip", "旅行"],
    ["water", "水"],
    ["week", "週"],
    ["woman", "女性"],
    ["word", "言葉、単語"],
    ["year", "年"],
    ["yesterday", "昨日"]
];