const $list = [
    ["price", "値段"],
    ["quiz", "クイズ"],
    ["racket", "ラケット"],
    ["ring", "指輪"],
    ["rock", "岩"],
    ["roof", "屋根"],
    ["rope", "ロープ"],
    ["ship", "船"],
    ["skin", "肌"],
    ["snow", "雪 / 雪が降る"],
    ["textbook", "教科書"],
    ["ticket", "チケット"],
    ["toilet", "トイレ"],
    ["towel", "タオル"],
    ["video", "ビデオ、映像"],
    ["violin", "バイオリン"],
    ["voice", "声"],
    ["wind", "風"],
    ["wood", "木材"],
    ["yacht", "ヨット"]
];