const $list = [
    ["asleep", "眠っている"],
    ["active", "活発な、アクティブな"],
    ["alive", "生きている"],
    ["basic", "基本的な、基礎の"],
    ["broad", "広い"],
    ["central", "中央の"],
    ["comfortable", "快適な、気持ちいい"],
    ["correct", "正確な"],
    ["creative", "創造的な"],
    ["dirty", "汚い"],
    ["dry", "乾いている"],
    ["fat", "太った"],
    ["honest", "正直な"],
    ["narrow", "(幅が)せまい"],
    ["polite", "礼儀正しい、丁寧な"],
    ["tough", "困難な"],
    ["unhappy", "悲しい、不幸な"],
    ["wet", "濡れている"],
    ["wise", "賢い"]
];