const $list = [
    ["mind", "心、気持ち / 気にする"],
    ["nature", "自然"],
    ["news", "ニュース"],
    ["office", "オフィス"],
    ["pet", "ペット"],
    ["phone", "電話"],
    ["point", "点、ポイント / 指差す"],
    ["power", "パワー、力"],
    ["present", "プレゼント"],
    ["rain", "雨 / 雨が降る"],
    ["reason", "理由"],
    ["rule", "ルール、規則"],
    ["shopping", "ショッピング、買い物"],
    ["sign", "記号/標識/～に署名する"],
    ["star", "星"],
    ["system", "システム、制度"],
    ["vacation", "休暇"],
    ["village", "村"],
    ["weekend", "週末"],
    ["yen", "日本円"]
];