const $list = [
    ["officer", "役人"],
    ["pamphlet", "パンフレット"],
    ["patient", "患者/病人、辛抱強い"],
    ["period", "時代"],
    ["pollution", "汚染"],
    ["purpose", "目的"],
    ["rhythm", "リズム"],
    ["scene", "シーン、光景"],
    ["site", "場所、遺跡"],
    ["subject", "主題/テーマ、科目/教科"],
    ["tail", "しっぽ"],
    ["tournament", "トーナメント"],
    ["traffic", "交通"],
    ["treasure", "宝物"],
    ["view", "景色/眺め、見解/考え"],
    ["wheelchair", "車イス"],
    ["unicycle", "一輪車"],
    ["uniform", "ユニフォーム、制服"],
    ["yogurt", "ヨーグルト"],
    ["website", "ウェブサイト"]
];