const $list = [
    ["peach", "桃"],
    ["pie", "パイ"],
    ["pilot", "パイロット"],
    ["pineapple", "パイナップル"],
    ["pizza", "ピザ"],
    ["plan", "計画 / ～を計画する"],
    ["playground", "校庭"],
    ["program", "プログラム、番組"],
    ["queen", "女王"],
    ["radish", "大根"],
    ["rectangle", "長方形"],
    ["restroom", "トイレ"],
    ["right", "右"],
    ["ruler", "定規"],
    ["sandwich", "サンドイッチ"],
    ["scissors", "はさみ"],
    ["shape", "形"],
    ["shirt", "シャツ"],
    ["shoulder", "肩"],
];