const $list = [
    ["apple", "りんご"],
    ["banana", "バナナ"],
    ["bath", "風呂"],
    ["bed", "ベッド"],
    ["bicycle", "自転車"],
    ["box", "箱"],
    ["breakfast", "朝食"],
    ["cake", "ケーキ"],
    ["cap", "帽子(キャップ)"],
    ["cat", "猫"],
    ["chair", "いす"],
    ["coffee", "コーヒー"],
    ["cup", "カップ"],
    ["dinner", "夕食"],
    ["dish", "皿、料理"],
    ["ear", "耳"],
    ["egg", "卵"],
    ["eraser", "消しゴム"],
    ["eye", "目"],
    ["face", "顔"]
];