const $list = [
    ["first", "1番目の、最初の/最初に"],
    ["second", "2番目の"],
    ["third", "3番目の"],
    ["fourth", "4番目の"],
    ["fifth", "5番目の"],
    ["sixth", "6番目の"],
    ["seventh", "7番目の"],
    ["eighth", "8番目の"],
    ["ninth", "9番目の"],
    ["tenth", "10番目の"],
    ["thirty", "30"],
    ["forty", "40"],
    ["fifty", "50"],
    ["sixty", "60"],
    ["seventy", "70"],
    ["eighty", "80"],
    ["ninety", "90"],
    ["hundred", "百"],
    ["thousand", "千"],
    ["zero", "0"]
];