const $list = [
    ["hill", "丘"],
    ["land", "土地/陸、着陸する"],
    ["leaf", "葉"],
    ["list", "リスト"],
    ["male", "男性(の)"],
    ["quarter", "4分の1"],
    ["record", "記録 / ～を記録する"],
    ["safety", "安全"],
    ["secret", "秘密(の)"],
    ["service", "サービス"],
    ["society", "社会"],
    ["stew", "シチュー"],
    ["stress", "ストレス / 強調"],
    ["taste", "味 / ～を味わう"],
    ["topic", "トピック、話題"],
    ["training", "トレーニング"],
    ["understanding", "理解"],
    ["wine", "ワイン"],
    ["yard", "庭 / ヤード(0.9m)"],
    ["zone", "ゾーン、地帯"]
];