const $list = [
    ["enemy", "敵"],
    ["fence", "フェンス"],
    ["fireplace", "暖炉"],
    ["fossil", "化石"],
    ["ghost", "おばけ"],
    ["hawk", "タカ"],
    ["height", "高さ"],
    ["honesty", "正直さ、誠実さ"],
    ["housework", "家事"],
    ["justice", "正義"],
    ["media", "メディア"],
    ["nest", "巣"],
    ["novel", "小説"],
    ["origin", "起源"],
    ["passenger", "乗客"],
    ["pharmacy", "薬局"],
    ["planet", "惑星"],
    ["politician", "政治家"],
    ["position", "位置"]
];