const $list = [
    ["onion", "たまねぎ"],
    ["orange", "オレンジ"],
    ["panda", "パンダ"],
    ["pen", "ペン"],
    ["pencil", "鉛筆"],
    ["pig", "豚"],
    ["police", "警察"],
    ["post", "ポスト"],
    ["potato", "ジャガイモ"],
    ["rabbit", "うさぎ"],
    ["rice", "米"],
    ["salad", "サラダ"],
    ["sheep", "羊"],
    ["singer", "歌手"],
    ["soup", "スープ"],
    ["sun", "太陽"],
    ["table", "テーブル"],
    ["television", "テレビ"],
    ["tiger", "トラ"],
    ["tomato", "トマト"]
];