const $list = [
    ["artist", "アーティスト、芸術家"],
    ["balloon", "風船"],
    ["bat", "バット"],
    ["bedroom", "寝室"],
    ["beef", "牛肉"],
    ["bell", "ベル、鈴、鐘"],
    ["belt", "ベルト、帯"],
    ["bench", "ベンチ"],
    ["butter", "バター"],
    ["camp", "キャンプ(する)"],
    ["cheese", "チーズ"],
    ["church", "教会"],
    ["finger", "指"],
    ["football", "フットボール"],
    ["gas", "ガス、気体"],
    ["gate", "ゲート、門"],
    ["grade", "級、学年"],
    ["gun", "銃"],
    ["happiness", "幸せ、幸福"],
    ["heat", "熱、暑さ"]
];