const $list = [
    ["level", "高さ / 水平"],
    ["luck", "運"],
    ["mask", "マスク"],
    ["neck", "首"],
    ["painting", "絵画"],
    ["plate", "皿"],
    ["pleasure", "喜び"],
    ["postcard", "はがき"],
    ["pot", "なべ"],
    ["stadium", "スタジアム、競技場"],
    ["sale", "セール"],
    ["sightseeing", "観光"],
    ["size", "サイズ"],
    ["snack", "軽食、おやつ"],
    ["socks", "靴下"],
    ["toast", "トースト"],
    ["toy", "おもちゃ"],
    ["war", "戦争"],
    ["winner", "勝者"]
];