const $list = [
    ["careful", "注意深い、慎重な"],
    ["convenient", "便利な"],
    ["cute", "かわいい"],
    ["deep", "深い"],
    ["excellent", "素晴らしい"],
    ["funny", "面白い"],
    ["empty", "空の"],
    ["full", "いっぱいの"],
    ["healthy", "健康な"],
    ["heavy", "重い"],
    ["impossible", "不可能な"],
    ["lucky", "幸運な"],
    ["perfect", "完全な"],
    ["possible", "可能な"],
    ["pretty", "かわいい / (副詞)かなり"],
    ["quiet", "静かな"],
    ["ready", "準備ができている"],
    ["real", "現実の、本当の"],
    ["safe", "安全な"],
    ["wide", "広い"]
];