const $list = [
    ["color", "色"],
    ["red", "赤"],
    ["blue", "青"],
    ["yellow", "黄色"],
    ["green", "緑"],
    ["purple", "紫"],
    ["pink", "ピンク"],
    ["orange", "オレンジ"],
    ["brown", "茶色"],
    ["black", "黒"],
    ["white", "白"],
    ["gray", "灰色"],
    ["rainbow", "虹"],
    ["picture", "絵、写真"],
    ["paint", "絵の具 / ～を描く"],
    ["art", "芸術"],
    ["beautiful", "美しい"],
    ["dark", "暗い"],
    ["light", "明るい"]
];