const $list = [
    ["activity", "活動"],
    ["aunt", "おば"],
    ["child", "子供"],
    ["children", "子供たち(複数形)"],
    ["city", "都市、市"],
    ["cousin", "いとこ"],
    ["course", "コース"],
    ["culture", "カルチャー、文化"],
    ["daughter", "娘"],
    ["evening", "夕方、夜"],
    ["event", "イベント、出来事"],
    ["example", "例"],
    ["experience", "経験 / ～を経験する"],
    ["festival", "祭り"],
    ["future", "未来、将来"],
    ["game", "ゲーム、試合"],
    ["grandchild", "孫"],
    ["grandfather", "祖父"],
    ["grandmother", "祖母"],
    ["history", "歴史"],
];