const $list = [
    ["principal", "校長 / 主な"],
    ["purse", "財布(小銭入れ)"],
    ["rate", "割合、率"],
    ["relationship", "関係性"],
    ["role", "役割"],
    ["shell", "貝殻"],
    ["source", "大元、源、出所"],
    ["speed", "スピード、速さ"],
    ["spirit", "精神、魂"],
    ["spot", "地点、場所"],
    ["storm", "嵐"],
    ["stream", "流れ"],
    ["term", "期間 / 学期"],
    ["tongue", "舌"],
    ["truth", "真実"],
    ["value", "価値"],
    ["vinegar", "お酢"],
    ["weight", "重さ"]
];