const $list = [
    ["Sunday", "日曜"],
    ["Monday", "月曜"],
    ["Tuesday", "火曜"],
    ["Wednesday", "水曜"],
    ["Thursday", "木曜"],
    ["Friday", "金曜"],
    ["Saturday", "土曜"],
    ["January", "1月"],
    ["February", "2月"],
    ["March", "3月"],
    ["April", "4月"],
    ["May", "5月"],
    ["June", "6月"],
    ["July", "7月"],
    ["August", "8月"],
    ["September", "9月"],
    ["October", "10月"],
    ["November", "11月"],
    ["December", "12月"],
    ["calendar", "カレンダー"]
];