const $list = [
    ["absent", "欠席の、不在の"],
    ["afraid", "怖れる"],
    ["alone", "孤独な、ひとりで"],
    ["angry", "怒っている"],
    ["cheap", "安い"],
    ["dangerous", "危険な"],
    ["excited", "興奮した"],
    ["expensive", "(値段が)高い"],
    ["far", "遠い"],
    ["free", "自由な、ひまな/無料の"],
    ["glad", "うれしい"],
    ["hard", "難しい/固い/一生懸命"],
    ["local", "地方の / 地元の"],
    ["natural", "自然の"],
    ["necessary", "必要な"],
    ["present", "現在の/出席している"],
    ["sick", "病気の"],
    ["strange", "変わった、奇妙な"],
    ["true", "本当の"],
    ["warm", "温かい、暖かい"]
];