const $list = [
    ["metal", "金属"],
    ["mile", "マイル(1.6km)"],
    ["noise", "騒音"],
    ["palace", "宮殿"],
    ["president", "大統領 / 社長"],
    ["sand", "砂"],
    ["sentence", "文"],
    ["sheet", "～枚/シート/シーツ"],
    ["signal", "信号"],
    ["silver", "銀(の)"],
    ["soybean", "大豆"],
    ["stick", "棒、杖"],
    ["stranger", "見知らぬ人"],
    ["survival", "サバイバル"],
    ["trash", "ゴミ"],
    ["trick", "手品 / いたずら"],
    ["tunnel", "トンネル"],
    ["wallet", "財布"],
    ["wedding", "結婚式"],
    ["wing", "つばさ"]
];