const $list = [
    ["agriculture", "農業"],
    ["ancestor", "祖先、先祖"],
    ["atmosphere", "大気 / 雰囲気"],
    ["attitude", "態度"],
    ["author", "著者"],
    ["behavior", "行為、振る舞い"],
    ["blossom", "花"],
    ["chimney", "煙突"],
    ["conference", "会議"],
    ["campaign", "キャンペーン"],
    ["cancer", "がん"],
    ["collection", "コレクション/収集"],
    ["competition", "競争、コンペ"],
    ["crop", "農作物"],
    ["democracy", "民主主義"],
    ["demonstration", "デモンストレーション"],
    ["dinosaur", "恐竜"],
    ["emergency", "緊急事態、非常事態"],
    ["era", "時代"]
];