const $list = [
    ["electricity", "電気"],
    ["elevator", "エレベーター"],
    ["energy", "エネルギー"],
    ["environment", "環境"],
    ["fashion", "ファッション、流行"],
    ["French", "フランス語/人、フランスの"],
    ["god", "神"],
    ["hero", "ヒーロー、英雄"],
    ["human", "人間"],
    ["leader", "リーダー"],
    ["magnet", "磁石"],
    ["meaning", "意味"],
    ["memory", "記憶"],
    ["menu", "メニュー"],
    ["middle", "真ん中、中間"],
    ["million", "百万"],
    ["mirror", "鏡"],
    ["ocean", "大海"],
    ["opinion", "意見"],
    ["prize", "賞"]
];