const $list = [
    ["globe", "地球、球体"],
    ["heaven", "天国"],
    ["interpreter", "通訳者"],
    ["knowledge", "知識"],
    ["lawyer", "弁護士"],
    ["marathon", "マラソン"],
    ["matter", "問題"],
    ["mystery", "謎"],
    ["official", "公式 / 公式の"],
    ["panic", "パニック(の)"],
    ["professor", "教授"],
    ["recipe", "レシピ"],
    ["relay", "リレー"],
    ["string", "糸、紐"],
    ["suburb", "郊外"],
    ["survey", "調査"],
    ["vote", "投票 / ～に投票する"],
    ["worth", "価値"]
];