const $list = [
    ["ant", "蟻"],
    ["bakery", "パン屋"],
    ["beach", "浜"],
    ["bear", "熊"],
    ["body", "体"],
    ["bread", "パン"],
    ["card", "カード"],
    ["carrot", "ニンジン"],
    ["castle", "城"],
    ["cherry", "さくらんぼ"],
    ["chicken", "鶏肉"],
    ["chocolate", "チョコレート"],
    ["classroom", "教室"],
    ["clock", "時計"],
    ["computer", "コンピューター"],
    ["cookie", "クッキー"],
    ["conversation", "会話"],
    ["corn", "トウモロコシ"],
    ["cow", "牛"]
];