const $list = [
    ["exhibition", "展示、展覧会"],
    ["experiment", "実験"],
    ["expression", "表現"],
    ["figure", "数字 / 人物 / 図"],
    ["flash", "フラッシュ"],
    ["gesture", "ジェスチャー"],
    ["handout", "配付物、ビラ"],
    ["hardship", "困難"],
    ["hatred", "憎しみ"],
    ["heritage", "文化的遺産"],
    ["highlight", "ハイライト、見せ場"],
    ["horizon", "地平線"],
    ["hurricane", "ハリケーン"],
    ["instrument", "楽器"],
    ["intelligence", "知能、知性"],
    ["invention", "発明"],
    ["material", "材料、物質"],
    ["mayor", "市長"],
    ["means", "方法"],
    ["minister", "大臣"]
];