const $list = [
    ["father", "父"],
    ["flower", "花"],
    ["food", "食べ物"],
    ["friend", "友達"],
    ["girl", "女の子"],
    ["group", "グループ"],
    ["hand", "手"],
    ["home", "家(に)"],
    ["house", "家"],
    ["Japan", "日本"],
    ["letter", "手紙"],
    ["library", "図書館"],
    ["light", "光/明るい/軽い"],
    ["lunch", "昼食"],
    ["man", "男性"],
    ["money", "お金"],
    ["morning", "朝"],
    ["mother", "母"],
    ["mountain", "山"],
    ["music", "音楽"]
];