const $list = [
    ["advice", "アドバイス、忠告"],
    ["animation", "アニメ、動画"],
    ["band", "バンド、楽団"],
    ["case", "場合、箱"],
    ["champion", "優勝者、チャンピオン"],
    ["church", "教会"],
    ["chef", "シェフ"],
    ["choice", "選択"],
    ["clerk", "店員、係員"],
    ["coach", "コーチ"],
    ["comic", "コミック"],
    ["custom", "習慣"],
    ["difficulty", "困難、苦労"],
    ["drum", "ドラム、太鼓"],
    ["garbage", "ゴミ"],
    ["fan", "ファン、扇/うちわ"],
    ["friendship", "友情"],
    ["hole", "穴"],
    ["importance", "重要性"],
    ["joke", "ジョーク、冗談"]
];