const $list = [
    ["age", "年齢 / 時代"],
    ["communication", "コミュニケーション"],
    ["concert", "コンサート"],
    ["dictionary", "辞書"],
    ["donut", "ドーナツ"],
    ["farm", "農場"],
    ["floor", "床 / ～階"],
    ["garden", "庭"],
    ["gift", "贈り物"],
    ["goal", "ゴール、目標"],
    ["gold", "金"],
    ["ground", "グラウンド、地面"],
    ["half", "半分、半分の"],
    ["hall", "ホール"],
    ["health", "健康"],
    ["husband", "夫"],
    ["island", "島"],
    ["line", "線、列"],
    ["medicine", "薬"]
];