const $list = [
    ["board", "板"],
    ["brain", "脳"],
    ["captain", "キャプテン"],
    ["chess", "チェス"],
    ["climate", "気候"],
    ["community", "地域社会、コミュニティ"],
    ["disaster", "災害"],
    ["drama", "ドラマ"],
    ["entertainment", "娯楽"],
    ["expert", "専門家、エキスパート"],
    ["farewell", "別れ"],
    ["flight", "フライト、飛ぶこと"],
    ["freedom", "自由"],
    ["fridge", "冷蔵庫"],
    ["fuel", "燃料"],
    ["humor", "ユーモア"],
    ["injury", "けが"],
    ["lamp", "ランプ、灯り"],
    ["movement", "動き / (社会的)運動"]
];