const $list = [
    ["certain", "確かな / とある"],
    ["classic", "古典的な"],
    ["colorful", "カラフルな"],
    ["efficient", "効率のよい"],
    ["golden", "金色の"],
    ["flat", "平らな"],
    ["latest", "最新の"],
    ["limited", "限定的な、限定の"],
    ["normal", "通常の"],
    ["opposite", "反対の"],
    ["pale", "顔色の悪い、青白い"],
    ["private", "個人的な / 私立の"],
    ["professional", "プロ/専門の"],
    ["regular", "規則正しい、通常の"],
    ["ridiculous", "ばかげた、愚かな"],
    ["skillful", "技術のある、熟練した"],
    ["terrible", "恐ろしい / ひどい"],
    ["tiny", "小さい"],
    ["usual", "いつもの"],
    ["wooden", "木の、木製の"]
];