const $list = [
    ["air", "空気"],
    ["American", "アメリカ人、アメリカの"],
    ["area", "エリア、地域"],
    ["baby", "赤ちゃん"],
    ["ball", "ボール"],
    ["chance", "機会"],
    ["classmate", "クラスメイト"],
    ["clothes", "服"],
    ["contest", "コンテスト"],
    ["door", "ドア"],
    ["end", "終わり/終わる/～を終える"],
    ["fact", "事実"],
    ["farmer", "農民、農家"],
    ["feeling", "感覚、気持ち"],
    ["fun", "楽しみ"],
    ["graph", "グラフ"],
    ["lesson", "レッスン、授業、教訓"],
    ["machine", "機械"],
    ["mail", "メール、手紙"],
    ["meeting", "ミーティング、打合せ"]
];