const $list = [
    ["heater", "ヒーター"],
    ["homestay", "ホームステイ"],
    ["hometown", "故郷"],
    ["image", "イメージ、画像"],
    ["joy", "喜び"],
    ["medal", "メダル"],
    ["moment", "瞬間、一瞬"],
    ["nursery", "保育園、託児所"],
    ["research", "調査、研究"],
    ["pair", "1組、対(ペア)"],
    ["partner", "パートナー、仲間"],
    ["sickness", "病気"],
    ["stomach", "胃"],
    ["subway", "地下鉄"],
    ["success", "成功"],
    ["timing", "タイミング"],
    ["volume", "ボリューム"],
    ["waiter", "ウエイター"],
    ["waitress", "ウエイトレス"],
    ["wave", "波"]
];