const $list = [
    ["be", "am, are, isの元の形"],
    ["will", "～だろう(未来)"],
    ["may", "～してもよい/かもしれない"],
    ["must", "～しなければならない"],
    ["should", "～すべきだ"],
    ["was", "am, isの過去形"],
    ["were", "areの過去形"],
    ["did", "doの過去形"],
    ["could", "canの過去形"],
    ["would", "willの過去形"],
    ["however", "しかしながら"],
    ["then", "その時 / それでは"],
    ["than", "～よりも"],
    ["still", "いまだに"],
    ["thing", "もの、こと"],
    ["something", "何か"],
    ["anything", "疑)何か/否)全く～ない"],
    ["nothing", "何もない"],
    ["too", "～過ぎる"]
];