const $list = [
    ["hobby", "趣味"],
    ["jacket", "ジャケット、上着"],
    ["kite", "凧(たこ)"],
    ["magic", "マジック"],
    ["nurse", "看護師"],
    ["oil", "油、オイル"],
    ["passport", "パスポート"],
    ["piece", "かけら"],
    ["pool", "プール"],
    ["prince", "王子"],
    ["race", "競争 / 人種"],
    ["radio", "ラジオ"],
    ["salt", "塩"],
    ["shampoo", "シャンプー"],
    ["shower", "シャワー"],
    ["sofa", "ソファ"],
    ["spoon", "スプーン"],
    ["sugar", "砂糖"],
    ["teammate", "チームメイト"],
    ["whale", "くじら"]
];