const $list = [
    ["surprising", "驚くべき"],
    ["brave", "勇敢な"],
    ["blind", "目の不自由な"],
    ["eastern", "東の、東部の"],
    ["international", "国際的な"],
    ["junior", "年下の、下級の"],
    ["mysterious", "不思議な、不可解な"],
    ["national", "国の、国民の"],
    ["native", "生まれつきの"],
    ["northern", "北の、北部の"],
    ["plastic", "プラスチック/ビニールの"],
    ["public", "公共の、公の"],
    ["senior", "年上の、上級の"],
    ["snowy", "雪の"],
    ["solar", "太陽の"],
    ["southern", "南の、南部の"],
    ["unique", "独特の、珍しい"],
    ["used", "中古の"],
    ["western", "西の、西洋/欧米の"],
    ["whole", "全体の、全ての"],
    ["be proud of", "～を誇りに思う"],
    ["crowded", "混雑した"],
    ["elderly", "年配の"],
    ["elementary", "基本の、初級の"],
    ["equal", "平等な、等しい"],
    ["homesick", "ホームシックの"],
    ["huge", "巨大な"],
    ["impressive", "印象的な、感動的な"],
    ["living", "生きている"],
    ["major", "主要な、大きな"],
    ["negative", "消極的な、否定的な"],
    ["nervous", "緊張した、神経質な"],
    ["peaceful", "平和な"],
    ["positive", "積極的な、前向きな"],
    ["round", "丸い / 円 / 回る"],
    ["scary", "怖ろしい"],
    ["shiny", "輝いている"],
    ["single", "たった1つの、ひとり用の"],
    ["thick", "厚い"],
    ["thin", "薄い、やせた"],
    ["worried", "心配している"],
    ["hopeless", "絶望した、望みのない"],
    ["normal", "通常の"],
    ["tiny", "小さい"],
    ["unhappy", "悲しい、不幸な"]
];