const $list = [
    ["ability", "能力"],
    ["audience", "聴衆"],
    ["award", "賞"],
    ["bit", "少量、少し"],
    ["bottom", "底"],
    ["breath", "呼吸、息"],
    ["cardboard", "段ボール、ボール紙"],
    ["chest", "胸"],
    ["chorus", "合唱"],
    ["crow", "カラス"],
    ["damage", "損害/～に損害を与える"],
    ["dust", "ちり、ほこり"],
    ["effect", "効果"],
    ["engine", "エンジン"],
    ["fear", "怖れ"],
    ["fisherman", "漁師"],
    ["jungle", "ジャングル"],
    ["manager", "マネージャー"],
    ["development", "開発 / 発展"],
    ["greenhouse gas", "温室効果ガス"],
    ["metal", "金属"],
    ["mile", "マイル(1.6km)"],
    ["noise", "騒音"],
    ["palace", "宮殿"],
    ["president", "大統領 / 社長"],
    ["sand", "砂"],
    ["sentence", "文"],
    ["sheet", "～枚/シート/シーツ"],
    ["signal", "信号"],
    ["silver", "銀(の)"],
    ["soybean", "大豆"],
    ["stick", "棒、杖"],
    ["stranger", "見知らぬ人"],
    ["survival", "サバイバル"],
    ["trash", "ゴミ"],
    ["trick", "手品 / いたずら"],
    ["tunnel", "トンネル"],
    ["wallet", "財布"],
    ["wedding", "結婚式"],
    ["wing", "つばさ"]
];