const $list = [
    ["advantage", "利点、有利な立場"],
    ["adventure", "冒険"],
    ["architect", "建築家"],
    ["astronaut", "宇宙飛行士"],
    ["carpenter", "大工"],
    ["effort", "努力"],
    ["glacier", "氷河"],
    ["government", "政府"],
    ["host", "主催者"],
    ["insect", "昆虫"],
    ["journalist", "記者、ジャーナリスト"],
    ["kangaroo", "カンガルー"],
    ["kilogram", "キログラム"],
    ["kilometer", "キロメートル"],
    ["laughter", "笑い"],
    ["law", "法律"],
    ["motto", "標語、モットー"],
    ["nation", "国家"],
    ["calligraphy", "書道"],
    ["global warming", "地球温暖化"],
    ["officer", "役人"],
    ["pamphlet", "パンフレット"],
    ["patient", "患者/病人、辛抱強い"],
    ["period", "時代 / 期間"],
    ["pollution", "汚染"],
    ["purpose", "目的"],
    ["rhythm", "リズム"],
    ["scene", "シーン、光景"],
    ["site", "場所、遺跡"],
    ["subject", "主題/テーマ、科目/教科"],
    ["tail", "しっぽ"],
    ["tournament", "トーナメント"],
    ["traffic", "交通"],
    ["treasure", "宝物"],
    ["view", "景色/眺め、見解/考え"],
    ["wheelchair", "車イス"],
    ["unicycle", "一輪車"],
    ["uniform", "ユニフォーム、制服"],
    ["yogurt", "ヨーグルト"],
    ["website", "ウェブサイト"]
];
