const $list = [
    ["excellent", "素晴らしい"],
    ["amazing", "驚くべき"],
    ["boring", "退屈な"],
    ["bright", "明るい、輝いている"],
    ["cheerful", "陽気な、(性格が)明るい"],
    ["clear", "きれいな / 明らかな"],
    ["cloudy", "曇りの"],
    ["common", "共通の、一般的な"],
    ["dead", "死んだ、死んでいる"],
    ["fair", "公平な"],
    ["true", "本当の"],
    ["final", "最後の、最終の"],
    ["forever", "永遠に、永久に"],
    ["fresh", "新鮮な"],
    ["global", "地球の、地球規模の"],
    ["helpful", "役立つ、助けになる"],
    ["lonely", "孤独な、さみしい"],
    ["loud", "(声/音が)大きい"],
    ["main", "主な、主要な"],
    ["original", "独自の、最初の"],
    ["personal", "個人的な"],
    ["powerful", "力強い"],
    ["rainy", "雨降りの"],
    ["serious", "重大な、真剣な"],
    ["several", "いくつかの"],
    ["shy", "内気な、恥ずかしがり屋の"],
    ["silent", "静かな"],
    ["similar", "似ている、同様の"],
    ["simple", "単純な"],
    ["smart", "賢い"],
    ["social", "社会的な"],
    ["sunny", "晴れた"],
    ["traditional", "伝統的な"],
    ["unfair", "不公平な、不正な"],
    ["various", "様々な"],
    ["wild", "野生の"],
    ["a lot of", "たくさんの"],
    ["be interested in", "～に興味がある"],
    ["pretty", "かわいい / (副詞)かなり"],
    ["usual", "いつもの"]
];