const $list = [
    ["home", "家(に)"],
    ["name", "名前 / ～に名付ける"],
    ["night", "夜"],
    ["number", "数、番号"],
    ["paper", "紙"],
    ["park", "公園"],
    ["parent", "親"],
    ["people", "人々"],
    ["person", "人"],
    ["question", "質問、問題"],
    ["river", "川"],
    ["room", "部屋"],
    ["school", "学校"],
    ["science", "科学、理科"],
    ["sea", "海"],
    ["shop", "店"],
    ["sister", "姉妹"],
    ["sky", "空"],
    ["song", "歌"],
    ["stamp", "切手"],
    ["station", "駅"],
    ["story", "ストーリー、話"],
    ["street", "通り"],
    ["student", "学生"],
    ["tea", "紅茶"],
    ["teacher", "先生"],
    ["team", "チーム"],
    ["time", "時間"],
    ["today", "今日"],
    ["tomorrow", "明日"],
    ["town", "町"],
    ["train", "電車 / ～を特訓する"],
    ["travel", "旅行 / 旅行する"],
    ["tree", "木"],
    ["water", "水"],
    ["week", "週"],
    ["woman", "女性"],
    ["word", "言葉、単語"],
    ["year", "年"],
    ["yesterday", "昨日"]
];