const $list = [
    ["peach", "桃"],
    ["pie", "パイ"],
    ["pilot", "パイロット"],
    ["pineapple", "パイナップル"],
    ["pizza", "ピザ"],
    ["plan", "計画 / ～を計画する"],
    ["queen", "女王"],
    ["radish", "大根"],
    ["rocket", "ロケット"],
    ["rose", "バラ"],
    ["restroom", "トイレ"],
    ["right", "右"],
    ["ruler", "定規"],
    ["sandwich", "サンドイッチ"],
    ["scissors", "はさみ"],
    ["shirt", "シャツ"],
    ["shoulder", "肩"],
    ["shrine", "神社"],
    ["post office", "郵便局"],
    ["playground", "校庭"],
    ["snake", "ヘビ"],
    ["south", "南"],
    ["square", "正方形"],
    ["stapler", "ホッチキス"],
    ["strawberry", "イチゴ"],
    ["sweater", "セーター"],
    ["teenager", "ティーンネイジャー"],
    ["teeth", "歯(複数形)"],
    ["telephone", "電話"],
    ["temple", "寺"],
    ["toe", "つま先"],
    ["tooth", "歯(単数形)"],
    ["triangle", "三角形"],
    ["umbrella", "傘"],
    ["vegetable", "野菜"],
    ["vest", "ベスト(服)"],
    ["watermelon", "スイカ"],
    ["west", "西"],
    ["wolf", "オオカミ"],
    ["zebra", "シマウマ"]
];