const $list = [
    ["hat", "帽子"],
    ["afternoon", "午後"],
    ["animal", "動物"],
    ["bag", "バッグ"],
    ["bike", "自転車"],
    ["bird", "鳥"],
    ["birthday", "誕生日"],
    ["book", "本"],
    ["boy", "男の子"],
    ["brother", "兄弟"],
    ["bus", "バス"],
    ["car", "車"],
    ["class", "クラス、授業"],
    ["club", "クラブ"],
    ["country", "国"],
    ["day", "日 / 日中"],
    ["doctor", "医者 / 博士"],
    ["dog", "犬"],
    ["dream", "夢 / 夢を見る"],
    ["English", "英語(の)"],
    ["family", "家族"],
    ["father", "父"],
    ["flower", "花"],
    ["food", "食べ物"],
    ["friend", "友達"],
    ["girl", "女の子"],
    ["group", "グループ"],
    ["hand", "手"],
    ["house", "家"],
    ["Japan", "日本"],
    ["letter", "手紙"],
    ["library", "図書館"],
    ["light", "光/明るい/軽い"],
    ["lunch", "昼食"],
    ["man", "男性"],
    ["money", "お金"],
    ["morning", "朝"],
    ["mother", "母"],
    ["mountain", "山"],
    ["music", "音楽"]
];