const $list = [
    ["trip", "旅行"],
    ["ant", "蟻"],
    ["bakery", "パン屋"],
    ["beach", "浜"],
    ["bear", "熊"],
    ["body", "体"],
    ["bread", "パン"],
    ["card", "カード"],
    ["carrot", "ニンジン"],
    ["castle", "城"],
    ["cherry", "さくらんぼ"],
    ["chicken", "鶏肉"],
    ["chocolate", "チョコレート"],
    ["classroom", "教室"],
    ["clock", "時計"],
    ["computer", "コンピューター"],
    ["cookie", "クッキー"],
    ["conversation", "会話"],
    ["corn", "トウモロコシ"],
    ["cow", "牛"],
    ["convenience store", "コンビニ"],
    ["crayon", "クレヨン"],
    ["cucumber", "きゅうり"],
    ["desk", "机"],
    ["dessert", "デザート"],
    ["doll", "人形"],
    ["duck", "アヒル"],
    ["east", "東"],
    ["elephant", "象"],
    ["foot", "足"],
    ["fox", "キツネ"],
    ["frog", "カエル"],
    ["glass", "ガラス / グラス"],
    ["glasses", "メガネ"],
    ["gloves", "手袋"],
    ["goat", "ヤギ"],
    ["gorilla", "ゴリラ"],
    ["department store", "デパート"],
    ["fire fighter", "消防士"],
    ["fire station", "消防署"],
    ["gas station", "ガソリンスタンド"],
    ["gym", "体育館"],
    ["hair", "髪"],
    ["hamburger", "ハンバーガー"],
    ["ink", "インク"],
    ["internet", "インターネット"],
    ["juice", "ジュース"],
    ["knee", "ひざ"],
    ["knife", "ナイフ"],
    ["koala", "コアラ"],
    ["lake", "湖"],
    ["left", "左"],
    ["leg", "脚"],
    ["lettuce", "レタス"],
    ["melon", "メロン"],
    ["mushroom", "キノコ"],
    ["newspaper", "新聞"],
    ["north", "北"],
    ["nuts", "ナッツ"],
    ["pants", "ズボン"],
    ["party", "パーティー"]
];