const $list = [
    ["anger", "怒り"],
    ["average", "平均(の)"],
    ["bamboo", "竹"],
    ["bone", "骨"],
    ["border", "境界、国境"],
    ["branch", "枝"],
    ["ceiling", "天井"],
    ["code", "記号、暗号"],
    ["conclusion", "結論"],
    ["condition", "状況 / 条件"],
    ["condominium", "マンション"],
    ["connection", "接続、繋がり"],
    ["content", "内容、中身"],
    ["costume", "衣装"],
    ["cotton", "綿"],
    ["cough", "せき"],
    ["cushion", "クッション"],
    ["distance", "距離"],
    ["drill", "訓練"],
    ["enemy", "敵"],
    ["fence", "フェンス"],
    ["fireplace", "暖炉"],
    ["fossil", "化石"],
    ["ghost", "おばけ"],
    ["hawk", "タカ"],
    ["height", "高さ"],
    ["honesty", "正直さ、誠実さ"],
    ["housework", "家事"],
    ["justice", "正義"],
    ["media", "メディア"],
    ["nest", "巣"],
    ["novel", "小説"],
    ["origin", "起源"],
    ["passenger", "乗客"],
    ["pharmacy", "薬局"],
    ["planet", "惑星"],
    ["politician", "政治家"],
    ["position", "位置"],
    ["hot spring", "温泉"],
    ["principal", "校長 / 主な"],
    ["purse", "財布(小銭入れ)"],
    ["rate", "割合、率"],
    ["role", "役割"],
    ["shell", "貝殻"],
    ["source", "大元、源、出所"],
    ["speed", "スピード、速さ"],
    ["spirit", "精神、魂"],
    ["spot", "地点、場所"],
    ["storm", "嵐"],
    ["stream", "流れ"],
    ["term", "期間 / 学期"],
    ["tongue", "舌"],
    ["truth", "真実"],
    ["value", "価値"],
    ["vinegar", "お酢"],
    ["weight", "重さ"],
    ["rain forest", "熱帯雨林"],
    ["relationship", "関係性"],
    ["vending machine", "自動販売機"]
];

