const $list = [
    ["attention", "注意、注目"],
    ["billion", "10億"],
    ["bomb", "爆弾"],
    ["cafeteria", "カフェテリア、学食"],
    ["career", "経歴、職業"],
    ["customer", "顧客"],
    ["championship", "大会 / 優勝"],
    ["charity", "チャリティー、慈善"],
    ["character", "性格・特色 / 人物 / 文字"],
    ["convenience", "便利さ"],
    ["corner", "コーナー、曲がり角"],
    ["crane", "鶴"],
    ["date", "日付"],
    ["designer", "デザイナー、設計者"],
    ["dolphin", "イルカ"],
    ["dome", "ドーム"],
    ["gram", "グラム"],
    ["headache", "頭痛"],
    ["industry", "産業"],
    ["interest", "興味、関心 / 利子"],
    ["match", "試合、勝負"],
    ["meter", "メートル"],
    ["octopus", "タコ"],
    ["peace", "平和"],
    ["percent", "パーセント"],
    ["performance", "演技、演奏"],
    ["poster", "ポスター"],
    ["presentation", "発表、プレゼンテーション"],
    ["reality", "現実、実際"],
    ["section", "部分、部門"],
    ["sense", "感覚 / 意味"],
    ["skill", "技術、スキル"],
    ["stationery", "文房具"],
    ["thought", "考え、思考"],
    ["tool", "道具 / 手段"],
    ["tower", "タワー"],
    ["track", "軌道・線路 / 陸上のトラック"],
    ["tuna", "マグロ"],
    ["wheel", "車輪"],
    ["physical education", "体育"]
];