const $list = [
    ["activity", "活動"],
    ["aunt", "おば"],
    ["child", "子供(単数形)"],
    ["children", "子供たち(複数形)"],
    ["city", "都市、市"],
    ["cousin", "いとこ"],
    ["course", "コース"],
    ["culture", "カルチャー、文化"],
    ["daughter", "娘"],
    ["evening", "夕方、夜"],
    ["event", "イベント、出来事"],
    ["example", "例"],
    ["experience", "経験 / ～を経験する"],
    ["festival", "祭り"],
    ["future", "未来、将来"],
    ["game", "ゲーム、試合"],
    ["history", "歴史"],
    ["grandchild", "孫"],
    ["grandfather", "祖父"],
    ["grandmother", "祖母"],
    ["hour", "時間(1時間)"],
    ["idea", "アイディア"],
    ["information", "情報"],
    ["job", "仕事"],
    ["language", "言語"],
    ["life", "生活 / 人生 / 命"],
    ["member", "メンバー"],
    ["minute", "分"],
    ["month", "月(1か月)"],
    ["noon", "昼 / 正午"],
    ["part", "部分"],
    ["player", "プレーヤー"],
    ["problem", "問題"],
    ["restaurant", "レストラン"],
    ["robot", "ロボット"],
    ["second", "秒"],
    ["son", "息子"],
    ["space", "空間 / 宇宙"],
    ["uncle", "おじ"],
    ["volunteer", "ボランティア"]
];